Secondary
Leon-Mbegera/Enumerables pull request #1
Opened 2021-03-24 15:55 UTC by ShoiraTa

# Project 2: Enumerable Methods

In this project, we wrote our own custom Ruby enumerable methods.

1. my_each
2. my_each_with_index
3. my_select
4. my_all?
5. my_any?
6. my_count
7. my_none?
8. my_inject
9. my_map

We ran test cases for every method we created.

2021-03-24 18:21 UTC, sinansevgi requested changes
# Status: Changes Required ♻️ 
----

Hello, team! 
You have done a great job. 
The methods are passing almost all of the test cases. 🧿 

Some of your methods are missing some behavior that is present in the original Enumerable methods. 

----
## Please check the inline comments for expected behaviors.

----
You can always contact me on [Slack](https://microverse-students.slack.com/team/U016UBBG4GZ) if you need assistance.

2021-03-24 18:21 UTC, sinansevgi commented on enumerable.rb
> +      raise LocalJump
- [x] You should write the exact name of the error to raise it.
```suggestion
      raise LocalJumpError
```

2021-03-24 18:21 UTC, sinansevgi commented on enumerable.rb
> +    array = to_a
- [ ] When you call each_with_index on ranges if a block is given it should return the range itself. 
Your my_each_with_index returns flatten the range to an array.

`(5..10).my_each_with_index{|num| num*2}` this expression should return `(5..10)` but your implementation returns `[5, 6, 7, 8, 9, 10]`

You can check the type of parameter before converting it to an array.

2021-03-24 18:21 UTC, sinansevgi commented on enumerable.rb
> +      return length
- [ ] #my_count method fails when I call it on a range.

It should return the number of items in the range
`(1..4).my_count` should return `4`
 `length` method doesn't work with ranges.

2021-03-24 18:21 UTC, sinansevgi commented on enumerable.rb
> +    else
- [ ]  When you pass symbol as an argument to #my_inject method should combine each element of the collection by applying the symbol as a named method.

 without initial value:
 `(5..10).my_inject(:+)` this expression should return `45`
 with initial value:
 `(5..10).inject(2, :*)` this expression should return `302400`

2021-03-25 08:39 UTC, ShoiraTa commented
Hello, 

We looked through all the comments and fixed the mentioned errors,

Thank you

2021-03-25 08:53 UTC, pacyL2K19 approved these changes
Approved :medal_military: 
Hello **Team** you made a great job so far, your readme file looks professional and all the tests pass congratulations :tada: 
Now feel free to merge this branch and submit the project 
Go ahead and keep it high 
Happy coding :desktop_computer:

2021-03-25 08:55 UTC, merged